import React, { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { FileText, ArrowRight, Pill, AlertCircle, Bookmark } from 'lucide-react';

const MedicineSearch = ({
  medicines = [],
  loading = false,
  currentPage = 1,
  totalPages = 1,
  onPageChange,
  bookmarkedMedicines = [],
  showCompletenessScore = false
}) => {

  // Calculate completeness percentage for display
  const getCompletenessPercentage = (medicine) => {
    const fields = ['name', 'genericName', 'drugClass', 'dosageForm', 'strength',
      'description', 'indications', 'sideEffects', 'warnings'];
    const filledFields = fields.filter(field => {
      const value = medicine[field];
      return value && value !== 'N/A' &&
        (Array.isArray(value) ? value.length > 0 : value.length > 10);
    });
    return Math.round((filledFields.length / fields.length) * 100);
  };
  const navigate = useNavigate();
  const listRef = useRef(null);

  // Animate list items when medicines change
  useGSAP(() => {
    if (medicines.length > 0 && !loading) {
      gsap.fromTo('.medicine-card',
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 0.4, stagger: 0.05, ease: "power2.out" }
      );
    }
  }, { scope: listRef, dependencies: [medicines, loading] });

  // Premium PDF design function
  const downloadPremiumPDF = (medicine) => {
    const doc = new jsPDF();
    doc.setProperties({
      title: `${medicine.name} - Medical Information`,
      subject: 'Medication Information Sheet',
      author: 'Prescripto Health'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = 0;

    // Header
    doc.setFillColor(20, 20, 20); // Dark gray/black
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PRESCRIPTO', margin, 26);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('OFFICIAL MEDICATION INFORMATION', pageWidth - margin, 26, { align: 'right' });

    // Content
    yPosition = 60;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(medicine.name, margin, yPosition);

    yPosition += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    doc.text(medicine.genericName || 'N/A', margin, yPosition);

    // Divider
    yPosition += 15;
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);

    // Details
    yPosition += 20;
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);

    const addField = (label, value) => {
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, margin, yPosition);
      doc.setFont('helvetica', 'normal');
      const splitText = doc.splitTextToSize(value || 'N/A', pageWidth - margin - 60);
      doc.text(splitText, margin + 40, yPosition);
      yPosition += (splitText.length * 6) + 6;
    };

    addField('Drug Class', medicine.drugClass);
    addField('Dosage Form', medicine.dosageForm);
    addField('Strength', medicine.strength);

    yPosition += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Description:', margin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    const description = doc.splitTextToSize(medicine.description || 'N/A', pageWidth - 2 * margin);
    doc.text(description, margin, yPosition);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Prescripto Health Systems', pageWidth / 2, pageHeight - 10, { align: 'center' });

    doc.save(`${medicine.name.replace(/\s+/g, '_')}_medical_info.pdf`);
  };

  if (loading) {
    return (
      <div className="space-y-4">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-40 bg-gray-100 dark:bg-gray-800 rounded-2xl animate-pulse"></div>
        ))}
      </div>
    );
  }

  return (
    <div ref={listRef} className="space-y-4">
      {medicines.map((medicine, index) => (
        <div
          key={index}
          className="medicine-card group bg-white dark:bg-gray-800 rounded-2xl p-4 sm:p-6 border border-gray-100 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600 hover:shadow-lg transition-all duration-300 cursor-pointer"
          onClick={() => medicine._id && navigate(`/medicines/${medicine._id}`)}
        >
          <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
            <div className="flex-1 min-w-0">
              <div className="flex items-center flex-wrap gap-2 mb-2">
                <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                  {medicine.name}
                </h3>

                {/* Bookmark Indicator - Next to Title */}
                {bookmarkedMedicines.includes(medicine._id) && (
                  <div className="flex items-center gap-1.5 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg border border-blue-200 dark:border-blue-800">
                    <Bookmark className="w-3.5 h-3.5 fill-current" />
                    <span className="text-xs font-semibold hidden sm:inline">Saved</span>
                  </div>
                )}

                <span className="px-2.5 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 text-xs font-medium rounded-full">
                  {medicine.drugClass || 'Medicine'}
                </span>
              </div>
              <p className="text-gray-500 dark:text-gray-400 font-medium mb-4">{medicine.genericName}</p>

              <div className="flex items-center gap-6 text-sm text-gray-500 dark:text-gray-400">
                <div>
                  <span className="block text-xs text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-0.5">Form</span>
                  {medicine.dosageForm || 'N/A'}
                </div>
                <div>
                  <span className="block text-xs text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-0.5">Strength</span>
                  {medicine.strength || 'N/A'}
                </div>

                {/* Data Completeness Indicator */}
                {showCompletenessScore && (
                  <div className="ml-auto">
                    <div className="flex items-center gap-2">
                      <div className="w-16 h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full transition-all ${getCompletenessPercentage(medicine) >= 80 ? 'bg-green-500' :
                              getCompletenessPercentage(medicine) >= 60 ? 'bg-primary' :
                                getCompletenessPercentage(medicine) >= 40 ? 'bg-yellow-500' : 'bg-orange-500'
                            }`}
                          style={{ width: `${getCompletenessPercentage(medicine)}%` }}
                        />
                      </div>
                      <span className="text-xs font-medium text-gray-600 dark:text-gray-400">
                        {getCompletenessPercentage(medicine)}%
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>

            <div className="flex items-center gap-2 w-full sm:w-auto mt-4 sm:mt-0">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  downloadPremiumPDF(medicine);
                }}
                className="p-3 text-gray-400 dark:text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-xl transition-all"
                title="Download PDF"
              >
                <FileText className="h-5 w-5" />
              </button>
              <button
                className="p-3 bg-gray-900 dark:bg-primary text-white rounded-xl hover:bg-gray-800 dark:hover:bg-primary/90 transition-all shadow-sm group-hover:shadow-md"
              >
                <ArrowRight className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      ))}

      {medicines.length === 0 && !loading && (
        <div className="text-center py-20">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-50 dark:bg-gray-800 mb-4">
            <Pill className="h-8 w-8 text-gray-300 dark:text-gray-600" />
          </div>
          <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-1">No medicines found.</h3>
          <p className="text-gray-500 dark:text-gray-400">Try adjusting your search or filters.</p>
        </div>
      )}

      {totalPages > 1 && (
        <div className="flex justify-center mt-12">
          <nav className="inline-flex bg-white dark:bg-gray-800 rounded-xl shadow-sm p-1 border border-gray-100 dark:border-gray-700">
            <button
              onClick={() => currentPage > 1 && onPageChange(currentPage - 1)}
              disabled={currentPage === 1}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${currentPage === 1
                ? 'text-gray-300 dark:text-gray-600 cursor-not-allowed'
                : 'text-gray-600 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white'
                }`}
            >
              Previous
            </button>

            <div className="flex items-center px-4 border-x border-gray-100 dark:border-gray-700 mx-1">
              <span className="text-sm text-gray-600 dark:text-gray-400">
                Page <span className="font-semibold text-gray-900 dark:text-white">{currentPage}</span> of <span className="font-semibold text-gray-900 dark:text-white">{totalPages}</span>
              </span>
            </div>

            <button
              onClick={() => currentPage < totalPages && onPageChange(currentPage + 1)}
              disabled={currentPage === totalPages}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${currentPage === totalPages
                ? 'text-gray-300 dark:text-gray-600 cursor-not-allowed'
                : 'text-gray-600 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white'
                }`}
            >
              Next
            </button>
          </nav>
        </div>
      )}
    </div>
  );
};

export default MedicineSearch;